[pytest]
addopts = -vs -rf --strict-markers --html-report=./report --title='PYTEST REPORT'

markers =
      smoke: quick critical-path checks
      regression: full coverage suite
      auth: test cases with authentication included